/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace libsbml {

using System;
using System.Runtime.InteropServices;

public class packageReferenceEntry : IDisposable {
	private HandleRef swigCPtr;
	protected bool swigCMemOwn;
	
	internal packageReferenceEntry(IntPtr cPtr, bool cMemoryOwn)
	{
		swigCMemOwn = cMemoryOwn;
		swigCPtr    = new HandleRef(this, cPtr);
	}
	
	internal static HandleRef getCPtr(packageReferenceEntry obj)
	{
		return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
	}
	
	internal static HandleRef getCPtrAndDisown (packageReferenceEntry obj)
	{
		HandleRef ptr = new HandleRef(null, IntPtr.Zero);
		
		if (obj != null)
		{
			ptr             = obj.swigCPtr;
			obj.swigCMemOwn = false;
		}
		
		return ptr;
	}

  ~packageReferenceEntry() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libsbmlPINVOKE.delete_packageReferenceEntry(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public string ref_l3v1 {
    set {
      libsbmlPINVOKE.packageReferenceEntry_ref_l3v1_set(swigCPtr, value);
    } 
    get {
      string ret = libsbmlPINVOKE.packageReferenceEntry_ref_l3v1_get(swigCPtr);
      return ret;
    } 
  }

  public packageReferenceEntry() : this(libsbmlPINVOKE.new_packageReferenceEntry(), true) {
  }

}

}
